### PR TITLE
Parser for HSBC bank

### PR DESCRIPTION
**Pull request by ddcatgg**
A new HsbcTransaction class holds the virtual account information.

### CODE REVIEW

**Comment by ddcatgg** [comment]
Why does Travis CI's hhvm test fail, what should I do?

**Comment by fruitl00p** [comment]
@ddcatgg HHVM is moving further and further away from PHP and you can update your PR (just make another commit to your branch) and remove the HHVM from travis.... I've been thinking of dropping that for a while now, since the [HHVM announcement](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html)

this is as good as time as any to push that forward :)

**Comment by ddcatgg** [comment]
@fruitl00p OK, I'll do that. thanks!

**Comment by fruitl00p** [comment]
@ddcatgg Thanks for your contribution! Great!

**Pull request merged**
