### PR TITLE
readme is arranged

### PR DESCRIPTION
**Pull request by SevanNerse**
Hey Robin!

If it is convenient for you, I would like to be the maintainer of the repo under your lead.

Regards
Sevan

### CODE REVIEW

**Comment by SevanNerse** [comment]
Any comments?

**Comment by fruitl00p** [comment]
@SevanNerse I've merged the PR but taking over as maintainer isnt something that i've thought about much. What are your plans / thoughts on why you want to become the maintainer anyway? Is there something you're missing?

**Comment by SevanNerse** [comment]
@fruitl00p I added some brand new engines to the repo as you know but I checked releases out and they are published rarely. That is why I asked for maintainer rights. Moreover, If you have thoughts related to improving the project, I would like to be part of it. Thanks for your response.

**Comment by fruitl00p** [comment]
@SevanNerse The reason for the low release rate is most updates don't actually warrant a new release in my mind :smile: 

I've invited you as contributor... Go at it :)

**Pull request merged**
