### PR TITLE
KNAB fixes

### PR DESCRIPTION
**Pull request by fruitl00p**
I've updated the KNAB parser based on private test file provided by KNAB

I've also implemented the start/end timestamp and price handling

### CODE REVIEW

**Comment by fruitl00p** [comment]
@SamMousa can you test your KNAB data with this PR? It should all work as intended as we now have some test data... but i'd like to make sure...

Thanks!

**Comment by SamMousa** [comment]
It's on my todo list.

**Comment by fruitl00p** [comment]
:+1:

**Comment by robgeerts** [comment]
KNAB has the option to export to 2 different MT940-files (the old one and a new structured one, I think as mentioned above. But the new one doesn't work. Is there a fix available?

**Comment by fruitl00p** [comment]
@robgeerts have you tried this new version of the code? This should support the newer structured MT940 format...

**Comment by robgeerts** [comment]
Yes, I've downloaded the code yesterday. With the old structured MT940 it works as expected.

**Comment by SamMousa** [comment]
@robgeerts Thanks for testing it, @fruitl00p, could this then be merged? And maybe a separate issue should be opened for the structured file?

**Comment by fruitl00p** [comment]
LGTM :+1:

**Comment by robgeerts** [comment]
Thanks but it doesn't work... for example, you're searching for REK: and NAAM: but both are not correct, in my MT940 from Knab it uses /NAME/, this is an example:

:61:1604290429D96,84N105NONREF//B6D29PGWUM0RDZ4H :86:/TRTP/SEPA ACCEPTGIRO/IBAN/NL83ABNA0437015300/BIC/ABNANL2AXXX /NAME/ACHMEA SCHADEVERZEKERINGEN N.V./EREF/5002100023310160 /REMI/EERSTE MAAND, MAART VERZEKERING 5002100023 310160

**Comment by SamMousa** [comment]
Are you referring to the structured or unstructured file? 

> KNAB has the option to export to 2 different MT940-files (the old one and a new structured one, I think as mentioned above. But the new one doesn't work. Is there a fix available?

You said the old one works. This PR was about the old one; so that is why it has been merged.

For the new file which has a different format, a new issue should be created.

**Comment by robgeerts** [comment]
Ok, sorry, I was talking about the new (structured) file.. 
I'll create a new issue..

**Pull request merged**
