### PR TITLE
Added the reference number "id" to the statement

### PR DESCRIPTION
**Pull request by bravoman**

### CODE REVIEW

**Comment by fruitl00p** [comment]
Isn't this the same as statement->getNumber()

**Comment by bravoman** [comment]
The getNumber gives the :28C: data which is not the same (at least for ING) as the :20: data.

**Comment by fruitl00p** [comment]
Hmmm... There is some controversy surrounding 28C and 20... Which is which... ? I feel the statement has a number (20) and a sequence (28c). The ID you propose feels awkward... 
(see i.e. https://www.ing.nl/media/ING_ftp_unstructured_mt940_942_format_description_the_netherlands_february_2014_2_tcm162-45688.pdf / http://www.abnamro.com/en/images/020_Clients_and_Services/070_MM4W/030_Technical/AOL_Reporting_Download_formats.pdf) Here they speak of MT940 message id as field 20 and what i used to refer to as the statement stuff via 28c... Maybe the current parsing of statementNumber should actually parse field 28c instead of 20 ?

**Comment by bravoman** [comment]
I think so yes, you already do this for the ING engine I believe.

**Comment by bravoman** [comment]
I was under the assumption that the other engines already use this 28c field for the statementNumber.

**Comment by bravoman** [comment]
Anyway, the ID code is not that important to me. But the debug option in the mt940 class is. Shall I just remove the ID (:20: reference code) from the merge request and leave the controversy for some later time? ;)

**Comment by fruitl00p** [comment]
That would be great, a single commit with the added debug flag :+1:

**Comment by fruitl00p** [comment]
Just to bring this issue to a close: the engine is injectable with the debug flag thereby adjustable... Wouldn't that workaround the issue of currying the $debug flag from one to the other?

**Comment by fruitl00p** [comment]
With the new developments around interfacing / injecting engines / priorities, this seems to bring the given issue to a full close. (if not, please re-open or recreate a new issue)

**Pull request closed without merging**
