### PR TITLE
Some fix for Spk since it uses 62M and 62F as well as 60M and 60F 

### PR DESCRIPTION
**Pull request by sven-codeculture**
Spk and some other german banks use 60M and 60F for start price and start date 
Futhermore they use 62F for the end date

Would be nice to get that online/to composer soon since we would need it for a project :)

(Docs at https://www.sparkasse-nuernberg.de/pdf/content/sfirm/mt940-satz.pdf?IFLBSERVERID=IF@@053@@IF)

Greetings Sven

### CODE REVIEW

**Comment by sven-codeculture** [comment]
Just added some more fix because some of the Spk test files that i got begin with an "-" so that the engine wasnt able to detect wich bank to use.

**Comment by sven-codeculture** [comment]
Just saw that the test failed. But i dont understand why it failed getting the 5.5 envs since this has nothing to do with my code.
Maybe you need to look over this.

Greeting Sven

**Comment by fruitl00p** [comment]
I've restarted as it seems it was an internal travis-ci intermittent failure... (atleast from what i can tell)

Is there a spec somewhere online for Spk? I'd like to verify but without a spec / documentation and tests this seems a bit flaky ;)

BTW with composer you can add your fork as the source for the package so you dont _have_ to wait for me to push a new release. (https://getcomposer.org/doc/05-repositories.md#vcs)

**Comment by fruitl00p** [comment]
Also i'd like to see the right coding standards (```{``` placement etc) I'm going for PSR2 just to be conforming to a widely known standard.

I've just pushed a small change to the factory for cleanup of the Spk fallback. (and adding an extra fallback _after_ the rest for Spk)

**Comment by sven-codeculture** [comment]
fixed branch to be mergeable again

**Comment by fruitl00p** [comment]
Thanks!

Do you have any tests / documentation from Spk for this? (I'd like to see verification)

Also could you squash the commits from your branch into one commit
```git rebase --interactive HEAD~<number-of-commits>```

That way the pull would be confined to one commit and clear up history too.. It might be asking a lot for such a tiny fix, but i'd like to keep some hold on quality. And the Spk engine is unverified today. So atleast i'd like to see some form of documentation and preferably tests

**Comment by sven-codeculture** [comment]
i just got some documentation for this and i already posted it in the first comment 
(https://www.sparkasse-nuernberg.de/pdf/content/sfirm/mt940-satz.pdf?IFLBSERVERID=IF@@053@@IF)
"Sparkasse" is a Group of Banks in germany and not a single one, so the documentation of Spk-Nuernberg should work.
I cant give you the testfiles i got since they are custumer specific, so im not allowed to give them out.
For the rebase: I dont get it working since ive never done this befor. This is maybe because i merged your changes into my changes befor.

**Comment by fruitl00p** [comment]
It looks good and indeed i missed the documentation link

The single commit should be doable via something like this:
``` git rebase -i origin/master ```
Change the pick on the second like to squash (or just ```s```), save the file and exit. You'll then get another editor with a commit message to edit. This is the soon to be single commit for this pullrequest. Save and exit. When pushing this new state use the ```--force``` flag and the commits already made should be replaced by the single :)

**Pull request closed without merging**
